name: Build Windows Packages

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag to release'
        default: '4.05-kuwa1'
        required: true
        type: string
  workflow_call:
    inputs:
      version:
        description: 'Version tag to release'
        default: '4.05-kuwa1'
        required: true
        type: string

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh
    strategy:
      matrix:
        arch: [x64, x86]
        config: [Release]
    
    env:
      VERSION: ${{ inputs.version }}
      ARCH: ${{ matrix.arch }}
      OS: win
    
    steps:
      - uses: actions/checkout@v3
      - name: Set up nmake
        uses: ilammy/msvc-dev-cmd@v1.13.0
        with:
          arch: ${{ matrix.arch }}
      - name: Build
        run: |
          mkdir build
          pushd build
          cmake .. -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=${{ matrix.config }}
          nmake
          popd

      - name: Package
        run: |
          $src = ".\build\xpdf\"
          $licenses = @(".\COPYING", ".\COPYING3")
          $dst = ".\dist\xpdf-tools-$env:VERSION-$env:OS-$env:ARCH"
          $dst_file = $dst + ".zip"

          $bin_dir = @{ x86 = "bin32"; x64 = "bin64"}[$env:ARCH]
          New-Item -ItemType Directory -Path $dst\$bin_dir

          #Filters by extension .exe
          $files = get-childitem $src
          $exes = $files | where {$_.extension -eq ".exe"}

          #Copies all the items to the specified destination
          $exes | Copy-Item -Destination $dst\$bin_dir\
          $licenses | Copy-Item -Destination $dst\

          Compress-Archive -Path $dst -DestinationPath $dst_file
          
      - name: Upload files to a GitHub release
        id: upload-release
        uses: svenstaro/upload-release-action@2.7.0
        continue-on-error: true
        with:
          file: ./dist/*.zip
          tag: ${{ inputs.version }}
          file_glob: true
          make_latest: false
          overwrite: true
        
      - uses: actions/upload-artifact@v3
        if: steps.upload-release.outcome == 'failure'
        with:
          name: ${{ inputs.version }}
          path: ./dist/*.zip